balance_general:
  # English
  - balance sheet
  - balancesheet
  - statement of financial position
  - sofp
  - financial position statement
  # Spanish / LatAm
  - balance general
  - BALANCE
  - balancesituacion
  - estado de situacion financiera
  - situacion patrimonial
  - estado de situacion patrimonial
  - balance de situacion
  - esf                # abreviatura
  # Portuguese (BR / PT)
  - balanco patrimonial
  - balanco_patrimonial
  - bp
  # French
  - bilan
  - etat de la situation financiere

cuenta_resultados:
  # English
  - income statement
  - incomestatement
  - profit and loss
  - profitloss
  - p&l
  - statement of operations
  - statement of earnings
  # Spanish / LatAm
  - estado de resultados
  - estadoderesultados
  - perdidas y ganancias
  - perdida y ganancias
  - cuenta de resultados
  - pyg       # abreviatura
  - eerr      # estados de resultados
  # Portuguese
  - demonstracao do resultado
  - dre
  # French
  - compte de resultat

flujo_caja:
  # English
  - cash flow
  - cashflow
  - cash flow statement
  - statement of cash flows
  - scf
  # Spanish / LatAm
  - flujo de caja
  - flujodecaja
  - flujo de efectivo
  - flujodeefectivo
  - estado de flujos de efectivo
  - efe
  # Portuguese
  - fluxo de caixa
  - dfc
  - demonstracao do fluxo de caixa
  # French
  - tableau des flux de tresorerie

paquete_eeff:
  - estados financieros
  - estadosfinancieros
  - eeff
  - paquete eeff
  - paqueteeeff
  - financial statements package
  - closing package
  - reporting package
  - annual report
  - informe de gestion
  - memoria anual
  - set of financial statements
  - conjunto de estados financieros

# ───────────── Modelos fiscales por país ───────────── #

modelo_fiscal_es:      # España
  - modelo 200
  - modelo 202
  - mod200
  - mod202
  - impuesto sobre sociedades
  - is 200
  - "200"
  - is_200

modelo_fiscal_mx:      # México (SAT)
  - declaracion anual sat
  - anexo 3 sat
  - anexo3
  - dictamen fiscal
  - sat anexo3
  - dicfisc
  - pago provisional isr
  - isr anual

modelo_fiscal_cl:      # Chile (SII)
  - formulario 22
  - f22
  - formulario 29
  - f29
  - f-22
  - formulario22
  - decl renta

modelo_fiscal_co:      # Colombia (DIAN)
  - formulario 110
  - form110
  - formato 2516
  - "2516"
  - declaracion renta personerias juridicas

modelo_fiscal_pe:      # Perú (SUNAT)
  - pdt 704
  - pdt704
  - formulario 710
  - form710
  - declaracion jurada anual isr

modelo_fiscal_ar:      # Argentina (AFIP)
  - formulario 713
  - f713
  - dj ganancias personas juridicas
  - ganancia web

modelo_fiscal_br:      # Brasil (Receita / SPED)
  - ecf
  - ecf sped
  - escrituração contábil fiscal
  - sped ecf
  - dirf
otro: []      # catch-all; se llena cuando nada coincide
